config/routes.rb
Rails.application.routes.draw do
  resources :incidents
  resources :concepts
  resources :cops 
  resources :evaluations
   root 'cops#index'
end

app/models/incident.rb
class Incident < ActiveRecord::Base
    self.inheritance_column = nil
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:tipo, :address, :fecha, :latitude, :longitude)
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_area :tipo %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.text_area :fecha %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incidents</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Address</th>
      <th>Date</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.tipo %></td>
        <td><%= incident.address %></td>
        <td><%= incident.fecha %></td>
        <td><%= incident.latitude %></td>
        <td><%= incident.longitude %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= render 'form' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @incident.tipo %>
</p>

<p>
  <strong>Address:</strong>
  <%= @incident.address %>
</p>

<p>
  <strong>Date:</strong>
  <%= @incident.fecha %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @incident.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @incident.longitude %>
</p>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>