config/routes.rb
Rails.application.routes.draw do
  resources :incidents
  resources :concepts
  resources :cops 
  resources :evaluations
   root 'cops#index'
end

app/models/cop.rb
class Cop < ActiveRecord::Base
    has_many :evaluations
end

app/controllers/cops_controller.rb
class CopsController < ApplicationController
  before_action :set_cop, only: [:show, :edit, :update, :destroy]
  # GET /cops
  # GET /cops.json
  def index

    if up_to_date?
      #reload_cops("http://201.144.220.174/infracciones/api/personal/acreditado")
    end
    
    @cops = Cop.all
    

    if params[:tipo] == 'incidentes'
      incidentes_fill
    elsif params[:tipo] == 'cop'
      @evaluacions= Evaluation.all
      @hash = Gmaps4rails.build_markers(@evaluacions) do |cop, marker|
        marker.lat  cop.latitude
        marker.lng  cop.longitude
        marker.infowindow cop.cop_id
      end
    else 
      incidentes_fill
    end
    @count =Evaluation.all.count 

    unless @count == 0
      @identificacion = Evaluation.all.sum(:identification) * 100 / @count
      @infraccion = Evaluation.all.sum(:infraccion) * 100 / @count
      @articulo = Evaluation.all.sum(:articulo)* 100 / @count
      @coincidio = Evaluation.all.sum(:coincidio)* 100 / @count
      @documents = Evaluation.all.sum(:documents)* 100 / @count
      @copy = Evaluation.all.sum(:copy)* 100 / @count
    else
      @identificacion = 0
      @infraccion = 0
      @articulo = 0
      @coincidio = 0
      @documents = 0
      @copy = 0
    end


  end

  def incidentes_fill
    @incidents = Incident.all
    @hash = Gmaps4rails.build_markers(@incidents) do |eva, marker|
      marker.lat  eva.latitude
      marker.lng  eva.longitude
      marker.infowindow eva.fecha
    end
  end

  # GET /cops/1
  # GET /cops/1.json
  def show
  end

  # GET /cops/new
  def new
  end

def get_evaluations
     
end

  # GET /cops/1/edit
  def edit
  end

  # POST /cops
  # POST /cops.json
  def create
    @cop = Cop.new(cop_params)

    respond_to do |format|
      if @cop.save
        format.html { redirect_to @cop, notice: 'cop was successfully created.' }
        format.json { render :show, status: :created, location: @cop }
      else
        format.html { render :new }
        format.json { render json: @cop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cops/1
  # PATCH/PUT /cops/1.json
  def update
    respond_to do |format|
      if @cop.update(cop_params)
        format.html { redirect_to @cop, notice: 'cop was successfully updated.' }
        format.json { render :show, status: :ok, location: @cop }
      else
        format.html { render :edit }
        format.json { render json: @cop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cops/1
  # DELETE /cops/1.json
  def destroy
    @cop.destroy
    respond_to do |format|
      format.html { redirect_to cops_url, notice: 'cop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

   def up_to_date? 
      if Cop.last.nil? || Cop.last.created_at < Time.now - 1.day
       return  true
      else
      return false
      end
  end


def reload_cops(url)
     json =  response = HTTParty.get(url)
      response = JSON.parse(json.body)
      Cop.delete_all
     response.each do |inf|
        Cop.create(nombre: inf['nombre_completo'], placa: inf['placa'] )
     end

end
    # Use callbacks to share common setup or constraints between actions.
    def set_cop
      @cop = cop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cop_params
      params.require(:cop).permit(:nombre, :placa, :identificacion, :infraccion, :articulo, :sancion, :devolvio, :copia, :latitud, :longitud)
    end
  end

app/views/cops/_form.html.erb
<%= form_for(@cop) do |f| %>
  <% if @cop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cop.errors.count, "error") %> prohibited this cop from being saved:</h2>

      <ul>
      <% @cop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_area :nombre %>
  </div>
  <div class="field">
    <%= f.label :placa %><br>
    <%= f.text_area :placa %>
  </div>
    <div class="field">
    <%= f.label :identificacion %><br>
    <%= f.text_area :identificacion %>
  </div>
    <div class="field">
    <%= f.label :infraccion %><br>
    <%= f.text_area :infraccion %>
  </div>
    <div class="field">
    <%= f.label :articulo %><br>
    <%= f.text_area :articulo %>
  </div>
    <div class="field">
    <%= f.label :sancion %><br>
    <%= f.text_area :sancion %>
  </div>
    <div class="field">
    <%= f.label :devolvio %><br>
    <%= f.text_area :devolvio %>
  </div>
    <div class="field">
    <%= f.label :copia %><br>
    <%= f.text_area :copia %>
  </div>
    <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_area :latitud %>
  </div>
    <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_area :longitud %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cops/edit.html.erb
<h1>Editing Infraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @cop %> |
<%= link_to 'Back', cops_path %>

app/views/cops/index.html.erb
    
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>



<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-text">
                    <span class="name"><img src="https://lh5.googleusercontent.com/-72GZ8uiqT58/VPyK3oZeRRI/AAAAAAAAAGc/KHIAEptyihc/w958-h155-no/InfraccionTitulo.png"></span>
                    <hr >
                    <span class="skills">Consulta quién te puede infraccionar y el tipo de sanción que te deben aplicar</span>
                </div>
            </div>
        </div>
    </div>
</header>


<section id="services" style="padding:50px 0 5px 0!important;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <br>
                <div class="col-md-6">
                    <div class="service-item">
                        <%= link_to "Evaluaciones", cops_path( :anchor => "mapa", :tipo => 'cop'),:class => 'btn btn-success btn-lg outlineverde'%>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="service-item">
                        <%= link_to "Incidentes",cops_path( :anchor => "mapa", :tipo => 'incidentes'), :class => 'btn btn-success btn-lg outlineverde'%>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<%#=@infractions.fist.latitud%>
<section id="mapa" >
    <div class="container">
        <div class="row">
  <div id="map" style='width: 100%; height: 400px;'></div>

        </div>
    </div>
</section>


<section id="progress" class="success">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                  <h3>Percepción ciudadana</h3>
                  <p>Evaluaciones otorgada por usuarios a los policias</p>
                  <br>
                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">
                          <div data-percentage="0%" style="width: <%=@identificacion%>%;" class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                   Identificación correcta <%= @identificacion%>%
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">
                          <div data-percentage="0%" style="width: <%=@infraccion%>%;" class="progress-bar progress-bar-info" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                    Infracción correcta <%= @infraccion%>%
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">
                          <div data-percentage="0%" style="width: <%=@articulo%>%;" class="progress-bar progress-bar-warning" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                   Fundamento en el reglamento <%= @articulo%>%
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">
                          <div data-percentage="0%" style="width: <%=@coincidio%>%;" class="progress-bar progress-bar-danger" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                    Sanción/Infracción correcta <%= @coincidio%>%;
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">
                          <div data-percentage="0%" style="width: <%=@documents%>%;" class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                    Devolución de documentos <%= @documents%>%
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-9 col-md-push-3 text-rigth">
                    <div class="progress">

                          <div data-percentage="0%" style="width: <%=@copy%>%;" class="progress-bar progress-bar-info" role="progressbar" aria-valuemin="0" aria-valuemax="0">
                          </div>
                    </div>
                  </div>
                  <div class="col-md-3 col-md-pull-9">
                    Copia de infracción <%= @copy%>%
                  </div>
                </div> 
            </div>
        </div>
</section>

<script type="text/javascript">

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/cops/new.html.erb
<h1>New Infraction</h1>

<%#= render 'form' %>

<%#= link_to 'Back', cops_path %>

app/views/cops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @infraction.nombre %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @infraction.placa %>
</p>

<p>
  <strong>Raking honestidad:</strong>
  <%= @infraction.raking_honestidad %>
</p>

<p>
  <strong>Raking trato:</strong>
  <%= @infraction.raking_trato %>
</p>

<%= link_to 'Edit', edit_cop_path(@infraction) %> |
<%= link_to 'Back', cops_path %>