config/routes.rb
Rails.application.routes.draw do
  resources :incidents
  resources :concepts
  resources :cops 
  resources :evaluations
   root 'cops#index'
end

app/models/concept.rb
class Concept < ActiveRecord::Base
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]

  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to concepts_url, notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params.require(:concept).permit(:infraccion, :monto, :corralon, :articulo, :fraccion, :parrafo, :inciso, :puntos)
    end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :infraccion %><br>
    <%= f.text_area :infraccion %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.text_area :monto %>
  </div>
  <div class="field">
    <%= f.label :corralon %><br>
    <%= f.text_area :corralon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing Concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<p id="notice"><%= notice %></p>

<section id="services">
  <div class="container">
    <div class="row">

    
<h1>Listing Concepts</h1>

<table>
  <thead>
    <tr>
      <th>Infraccion</th>
      <th>Monto</th>
      <th>Corralon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.infraccion %></td>
        <td><%= concept.monto %></td>
        <td><%= concept.corralon %></td>
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
  </div>
</section>

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>

<section id="services">
	<div class="container">
		<div class="row">
				<%= render 'form' %>
		</div>
	</div>
</section>


<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Infraccion:</strong>
  <%= @concept.infraccion %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @concept.monto %>
</p>

<p>
  <strong>Corralon:</strong>
  <%= @concept.corralon %>
</p>

<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>